In [20]:
# import required library

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix

import warnings
warnings.filterwarnings('ignore')

## first create model form doctor

In [21]:
# load datase
df = pd.read_csv("./data2/doctor_data.csv")

In [22]:
df.head()

,Gender,Family Heart Disease,Diabetes,High Blood Pressure,High LDL Cholesterol,Sugar Consumption,lifstyle_score,age_bmi_risk,health risk
0,0,1,0,1,0,1,0.511301,0.374804,High
1,1,1,1,0,0,1,0.674302,0.493775,Medium
2,0,0,0,0,1,0,0.419191,0.365665,Low
3,1,1,0,1,1,2,0.404439,0.155783,High
4,0,1,1,1,0,2,0.387571,0.315331,High

In [23]:
df.shape

(10000, 9)

In [24]:
df.isnull().sum()

Gender                  0
Family Heart Disease    0
Diabetes                0
High Blood Pressure     0
High LDL Cholesterol    0
Sugar Consumption       0
lifstyle_score          0
age_bmi_risk            0
health risk             0
dtype: int64

In [25]:
df['health risk'] = df['health risk'].map({'High' :2 , 'Low' : 0 , "Medium" : 1})

saprate x and y

In [26]:
x = df.drop(['health risk'] , axis=1)
y = df['health risk']

In [27]:
# trin test split

x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.25 , random_state=9)

In [28]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(7500, 8)
(7500,)
(2500, 8)
(2500,)

In [29]:
y_train

5047    0
3625    2
4446    0
8898    1
3766    1
       ..
6200    0
501     1
6782    0
4444    2
8574    2
Name: health risk, Length: 7500, dtype: int64

In [30]:
df['health risk'].value_counts()

health risk
2    4762
1    3884
0    1354
Name: count, dtype: int64

## Randomforest - 

no. of decision tree used to predict and here no need of balanced data

In [37]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(class_weight='balanced')
forest.fit(x_train , y_train)
y_pred = forest.predict(x_test)
print(f"accuracy score by random forest is : {accuracy_score(y_test , y_pred)}")

# matric = confusion_matrix(y_test , y_pred)
# plt.figure(figsize=(7 , 5))
# sns.heatmap(matric , cmap='coolwarm' , annot=True)
# plt.show()
print(f"confusion metrics :")
print(confusion_matrix(y_test , y_pred))

accuracy score by random forest is : 0.9772
confusion metrics :
[[ 314   16    0]
 [   3  938   22]
 [   0   16 1191]]

## Balanced the data first by SMOTE

In [ ]:
# import sys
# !{sys.executable} -m pip install imblearn

Collecting imblearn
  Using cached imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Using cached imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\hp\heath_risk_prediction\venv\lib\site-packages (from imbalanced-learn->imblearn) (2.4.4)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\hp\heath_risk_prediction\venv\lib\site-packages (from imbalanced-learn->imblearn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\hp\heath_risk_prediction\venv\lib\site-packages (from imbalanced-learn->imblearn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn->imblearn)
  Using cached sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\hp\heath_risk_prediction\venv\lib\site-packages (from imbalanced-learn->imblearn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\hp\heath_risk_prediction\venv\lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)
Using cached imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Using cached imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Using cached sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn, imblearn
Successfully installed imbalanced-learn-0.14.1 imblearn-0.0 sklearn-compat-0.1.5

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
# from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import SMOTE

smote = SMOTE()

x_smote , y_smote  = smote.fit_resample(x_train , y_train)
print(x_smote.shape)
print(y_smote.shape)

(10665, 8)
(10665,)

## Gradiant boosting

In [45]:
from sklearn.ensemble import GradientBoostingClassifier

grad = GradientBoostingClassifier()
grad.fit(x_smote , y_smote)
y_pred = grad.predict(x_test)

print(f"accuracy by gradient boosting is : {accuracy_score(y_test , y_pred)}")

print(f"confusion matrix is : ")
print(confusion_matrix(y_test , y_pred))

accuracy by gradient boosting is : 0.9484
confusion matrix is :
[[ 312   18    0]
 [  23  918   22]
 [   0   66 1141]]

## Decision tree

In [46]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()
tree.fit(x_smote , y_smote)
y_pred = tree.predict(x_test)

print(f"accuracy by gradient boosting is : {accuracy_score(y_test , y_pred)}")

print(f"confusion matrix is : ")
print(confusion_matrix(y_test , y_pred))

accuracy by gradient boosting is : 0.9712
confusion matrix is :
[[ 320   10    0]
 [  16  920   27]
 [   0   19 1188]]

In the medical dataset if patient actual in high risk but predict as low/medium that is create a problem 

here we can see RandomForest pediction low where it predicted high as low risk, hence we should go with random forest

## Hyper parameter tunning

In [ ]:
# from sklearn.model_selection import GridSearchCV

# param ={
#     'criterion' : ['gini' , 'entropy' ,'log_loss'],
#     'n_estimators' : [100 , 200 , 300],
#     'max_depth' : [5 , 6 , 7],
# }

# model = RandomForestClassifier(class_weight='balanced')
# grid = GridSearchCV(model , cv=5 , param_grid=param , verbose=2)

In [ ]:
# grid.fit(x_train , y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] END ......criterion=gini, max_depth=5, n_estimators=100; total time=   3.9s
[CV] END ......criterion=gini, max_depth=5, n_estimators=100; total time=   0.9s
[CV] END ......criterion=gini, max_depth=5, n_estimators=100; total time=   0.8s
[CV] END ......criterion=gini, max_depth=5, n_estimators=100; total time=   0.8s
[CV] END ......criterion=gini, max_depth=5, n_estimators=100; total time=   0.6s
[CV] END ......criterion=gini, max_depth=5, n_estimators=200; total time=   1.7s
[CV] END ......criterion=gini, max_depth=5, n_estimators=200; total time=   1.5s
[CV] END ......criterion=gini, max_depth=5, n_estimators=200; total time=   1.4s
[CV] END ......criterion=gini, max_depth=5, n_estimators=200; total time=   1.4s
[CV] END ......criterion=gini, max_depth=5, n_estimators=200; total time=   1.8s
[CV] END ......criterion=gini, max_depth=5, n_estimators=300; total time=   3.5s
[CV] END ......criterion=gini, max_depth=5, n_estimators=300; total time=   2.4s
[CV] END ......criterion=gini, max_depth=5, n_estimators=300; total time=   2.0s
[CV] END ......criterion=gini, max_depth=5, n_estimators=300; total time=   2.3s
[CV] END ......criterion=gini, max_depth=5, n_estimators=300; total time=   2.0s
[CV] END ......criterion=gini, max_depth=6, n_estimators=100; total time=   0.7s
[CV] END ......criterion=gini, max_depth=6, n_estimators=100; total time=   0.7s
[CV] END ......criterion=gini, max_depth=6, n_estimators=100; total time=   0.7s
[CV] END ......criterion=gini, max_depth=6, n_estimators=100; total time=   1.0s
[CV] END ......criterion=gini, max_depth=6, n_estimators=100; total time=   0.7s
[CV] END ......criterion=gini, max_depth=6, n_estimators=200; total time=   1.5s
[CV] END ......criterion=gini, max_depth=6, n_estimators=200; total time=   1.4s
[CV] END ......criterion=gini, max_depth=6, n_estimators=200; total time=   1.7s
[CV] END ......criterion=gini, max_depth=6, n_estimators=200; total time=   1.4s
[CV] END ......criterion=gini, max_depth=6, n_estimators=200; total time=   1.4s
[CV] END ......criterion=gini, max_depth=6, n_estimators=300; total time=   2.6s
[CV] END ......criterion=gini, max_depth=6, n_estimators=300; total time=   2.2s
[CV] END ......criterion=gini, max_depth=6, n_estimators=300; total time=   2.4s
[CV] END ......criterion=gini, max_depth=6, n_estimators=300; total time=   2.3s
[CV] END ......criterion=gini, max_depth=6, n_estimators=300; total time=   2.6s
[CV] END ......criterion=gini, max_depth=7, n_estimators=100; total time=   1.3s
[CV] END ......criterion=gini, max_depth=7, n_estimators=100; total time=   1.3s
[CV] END ......criterion=gini, max_depth=7, n_estimators=100; total time=   0.9s
[CV] END ......criterion=gini, max_depth=7, n_estimators=100; total time=   0.7s
[CV] END ......criterion=gini, max_depth=7, n_estimators=100; total time=   0.7s
[CV] END ......criterion=gini, max_depth=7, n_estimators=200; total time=   3.2s
[CV] END ......criterion=gini, max_depth=7, n_estimators=200; total time=   1.6s
[CV] END ......criterion=gini, max_depth=7, n_estimators=200; total time=   1.9s
[CV] END ......criterion=gini, max_depth=7, n_estimators=200; total time=   1.6s
[CV] END ......criterion=gini, max_depth=7, n_estimators=200; total time=   1.6s
[CV] END ......criterion=gini, max_depth=7, n_estimators=300; total time=   2.8s
[CV] END ......criterion=gini, max_depth=7, n_estimators=300; total time=   2.3s
[CV] END ......criterion=gini, max_depth=7, n_estimators=300; total time=   2.6s
[CV] END ......criterion=gini, max_depth=7, n_estimators=300; total time=   2.3s
[CV] END ......criterion=gini, max_depth=7, n_estimators=300; total time=   2.5s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=100; total time=   1.4s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=100; total time=   0.8s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=100; total time=   0.8s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=100; total time=   0.8s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=100; total time=   0.8s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=200; total time=   2.2s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=200; total time=   1.7s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=200; total time=   2.4s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=200; total time=   1.9s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=200; total time=   1.6s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=300; total time=   2.9s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=300; total time=   2.6s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=300; total time=   2.9s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=300; total time=   2.5s
[CV] END ...criterion=entropy, max_depth=5, n_estimators=300; total time=   2.9s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=100; total time=   0.9s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=100; total time=   0.9s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=100; total time=   0.9s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=100; total time=   1.0s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=100; total time=   1.3s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=200; total time=   2.9s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=200; total time=   2.2s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=200; total time=   1.9s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=200; total time=   1.9s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=200; total time=   2.1s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=300; total time=   2.9s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=300; total time=   3.8s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=300; total time=   2.8s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=300; total time=   3.1s
[CV] END ...criterion=entropy, max_depth=6, n_estimators=300; total time=   3.1s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=100; total time=   1.0s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=100; total time=   1.0s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=100; total time=   1.0s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=100; total time=   1.0s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=100; total time=   1.5s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=200; total time=   2.5s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=200; total time=   2.2s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=200; total time=   2.2s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=200; total time=   1.9s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=200; total time=   2.3s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=300; total time=   3.2s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=300; total time=   4.4s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=300; total time=   3.4s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=300; total time=   7.2s
[CV] END ...criterion=entropy, max_depth=7, n_estimators=300; total time=   3.3s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=100; total time=   1.6s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=100; total time=   0.9s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=100; total time=   1.0s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=100; total time=   1.5s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=100; total time=   1.3s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=200; total time=   1.9s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=200; total time=   1.7s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=200; total time=   1.9s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=200; total time=   1.7s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=200; total time=   1.6s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=300; total time=   2.9s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=300; total time=   2.9s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=300; total time=   2.8s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=300; total time=   2.5s
[CV] END ..criterion=log_loss, max_depth=5, n_estimators=300; total time=   2.8s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=100; total time=   0.9s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=100; total time=   0.8s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=100; total time=   0.8s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=100; total time=   1.0s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=100; total time=   1.1s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=200; total time=   2.1s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=200; total time=   1.9s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=200; total time=   3.2s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=200; total time=   1.8s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=200; total time=   2.1s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=300; total time=   3.8s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=300; total time=   3.3s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=300; total time=   3.1s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=300; total time=   2.8s
[CV] END ..criterion=log_loss, max_depth=6, n_estimators=300; total time=   3.4s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=100; total time=   1.0s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=100; total time=   1.0s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=100; total time=   0.9s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=100; total time=   1.2s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=100; total time=   0.9s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=200; total time=   2.0s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=200; total time=   2.3s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=200; total time=   2.0s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=200; total time=   2.1s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=200; total time=   2.2s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=300; total time=   3.1s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=300; total time=   3.3s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=300; total time=   3.2s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=300; total time=   3.1s
[CV] END ..criterion=log_loss, max_depth=7, n_estimators=300; total time=   3.2s

GridSearchCV(cv=5, estimator=RandomForestClassifier(class_weight='balanced'),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [5, 6, 7],
                         'n_estimators': [100, 200, 300]},
             verbose=2)

In [ ]:
# grid.best_params_

{'criterion': 'log_loss', 'max_depth': 7, 'n_estimators': 200}

In [56]:
final_model = RandomForestClassifier(class_weight='balanced' , criterion='log_loss' , max_depth=7 , n_estimators=200)

final_model.fit(x_train , y_train)
y_pred = final_model.predict(x_test)

print(f"accuracy by random forest :  {accuracy_score(y_test , y_pred)}")
print(f"confusion matrics :")
print(confusion_matrix(y_test , y_pred))

accuracy by random forest :  0.9588
confusion matrics :
[[ 320   10    0]
 [  22  919   22]
 [   0   49 1158]]

Even simple random forest has high accuracy go with gridsearchcv because low chance to overfit

In [61]:
import joblib

joblib.dump(final_model , "doctor_model.pkl")

['doctor_model.pkl']

### Patient model

In [83]:
# load the data

df = pd.read_csv('./data2/patient_data.csv')

In [84]:
df.head()

,Age,Gender,Exercise Habits,Smoking,Family Heart Disease,Diabetes,High Blood Pressure,Alcohol Consumption,Stress Level,Sugar Consumption,heakth risk
0,56.0,0,2,1,1,0,1,2,1,1,High
1,69.0,1,2,0,1,1,0,1,2,1,Medium
2,46.0,0,0,0,0,0,0,0,0,0,Low
3,32.0,1,2,1,1,0,1,0,2,2,Medium
4,60.0,0,0,1,1,1,1,0,2,2,High

In [85]:
df.isnull().sum()

Age                     0
Gender                  0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
High Blood Pressure     0
Alcohol Consumption     0
Stress Level            0
Sugar Consumption       0
heakth risk             0
dtype: int64

In [88]:
df['health risk'] = df['heakth risk'].map({'High' : 2 , 'Low' : 0 , 'Medium' : 1})

In [90]:
df.drop('heakth risk' , axis=1 , inplace=True)

In [89]:
df.head()

,Age,Gender,Exercise Habits,Smoking,Family Heart Disease,Diabetes,High Blood Pressure,Alcohol Consumption,Stress Level,Sugar Consumption,heakth risk,health risk
0,56.0,0,2,1,1,0,1,2,1,1,High,2
1,69.0,1,2,0,1,1,0,1,2,1,Medium,1
2,46.0,0,0,0,0,0,0,0,0,0,Low,0
3,32.0,1,2,1,1,0,1,0,2,2,Medium,1
4,60.0,0,0,1,1,1,1,0,2,2,High,2

In [91]:
# saprate x and y

x = df.drop("health risk" , axis=1)
y = df['health risk']  # by mistake put is heakth risk it is health risk

In [92]:
df.head()

,Age,Gender,Exercise Habits,Smoking,Family Heart Disease,Diabetes,High Blood Pressure,Alcohol Consumption,Stress Level,Sugar Consumption,health risk
0,56.0,0,2,1,1,0,1,2,1,1,2
1,69.0,1,2,0,1,1,0,1,2,1,1
2,46.0,0,0,0,0,0,0,0,0,0,0
3,32.0,1,2,1,1,0,1,0,2,2,1
4,60.0,0,0,1,1,1,1,0,2,2,2

In [93]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.25 , random_state=9)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(7500, 10)
(7500,)
(2500, 10)
(2500,)

## Randomforest

In [94]:
forest2 = RandomForestClassifier(class_weight='balanced')

forest2.fit(x_train , y_train)
y_pred = forest2.predict(x_test)
print(f"accuracy by forest is : {accuracy_score(y_test , y_pred)}")

print(f"confusion matric : ")
print(confusion_matrix(y_test , y_pred))

accuracy by forest is : 0.944
confusion matric :
[[ 635   50    0]
 [  20 1038   17]
 [   0   53  687]]

In [95]:
smote = SMOTE()

x_smote , y_smote = smote.fit_resample(x_train , y_train)

print(x_smote.shape)
print(y_smote.shape)

(9411, 10)
(9411,)

## Decision tree

In [ ]:
tree2 = DecisionTreeClassifier()
tree2.fit(x_smote , y_smote)
y_pred = tree2.predict(x_test)
print(f"accuracy by tree is : {accuracy_score(y_test , y_pred)}")

print(f"confusion matric : ")
print(confusion_matrix(y_test , y_pred))

accuracy by forest is : 0.8664
confusion matric :
[[602  82   1]
 [ 69 894 112]
 [  0  70 670]]

## SVM

In [ ]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_smote , y_smote)
y_pred = svc.predict(x_test)
print(f"accuracy by svc is : {accuracy_score(y_test , y_pred)}")

print(f"confusion matric : ")
print(confusion_matrix(y_test , y_pred))

accuracy by forest is : 0.8012
confusion matric :
[[523 162   0]
 [ 29 898 148]
 [  0 158 582]]

## Gradient boosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

grad2 = GradientBoostingClassifier()

grad2.fit(x_smote , y_smote)
y_pred = grad2.predict(x_test)
print(f"accuracy by gradient is : {accuracy_score(y_test , y_pred)}")

print(f"confusion matric : ")
print(confusion_matrix(y_test , y_pred))

accuracy by forest is : 0.9472
confusion matric :
[[662  23   0]
 [ 23 978  74]
 [  0  12 728]]

gradient boosting given best accuracy go with gradient boosting

## Tunning

In [ ]:
# from sklearn.model_selection import GridSearchCV

# param = {
#     'learning_rate' : [0.1 , 0.2 ,0.3],
#     'loss': ['log_loss', 'deviance', 'exponential'],
#     'n_estimators' : [100 , 200 , 300]
# }

# model = GradientBoostingClassifier()

# grid = GridSearchCV(model , cv=5 , param_grid=param , verbose=2)

In [ ]:
# grid.fit(x_smote , y_smote)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=100; total time=   3.6s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=100; total time=   2.3s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=100; total time=   3.3s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=100; total time=   2.2s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=100; total time=   2.2s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=200; total time=   4.3s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=200; total time=   4.7s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=200; total time=   5.6s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=200; total time=   4.6s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=200; total time=   4.4s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=300; total time=   6.4s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=300; total time=   6.4s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=300; total time=   6.5s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=300; total time=   6.4s
[CV] END .learning_rate=0.1, loss=log_loss, n_estimators=300; total time=   6.3s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.1, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.1, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=100; total time=   2.3s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=100; total time=   2.0s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=100; total time=   2.0s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=100; total time=   2.2s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=100; total time=   2.4s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=200; total time=   4.3s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=200; total time=   4.2s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=200; total time=   4.2s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=200; total time=   4.3s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=200; total time=   4.2s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=300; total time=   6.6s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=300; total time=   6.5s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=300; total time=   6.3s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=300; total time=   6.9s
[CV] END .learning_rate=0.2, loss=log_loss, n_estimators=300; total time=   6.4s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.2, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.2, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=100; total time=   2.0s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=100; total time=   2.1s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=100; total time=   2.1s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=100; total time=   2.0s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=100; total time=   2.1s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=200; total time=   5.3s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=200; total time=   4.2s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=200; total time=   4.1s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=200; total time=   4.2s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=200; total time=   4.1s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=300; total time=   6.3s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=300; total time=   6.7s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=300; total time=   6.5s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=300; total time=   6.3s
[CV] END .learning_rate=0.3, loss=log_loss, n_estimators=300; total time=   6.2s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=100; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=200; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END .learning_rate=0.3, loss=deviance, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=100; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=200; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=300; total time=   0.0s
[CV] END learning_rate=0.3, loss=exponential, n_estimators=300; total time=   0.0s

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.1, 0.2, 0.3],
                         'loss': ['log_loss', 'deviance', 'exponential'],
                         'n_estimators': [100, 200, 300]},
             verbose=2)

In [ ]:
# grid.best_params_

{'learning_rate': 0.3, 'loss': 'log_loss', 'n_estimators': 200}

In [ ]:
final_model = GradientBoostingClassifier( learning_rate= 0.3, loss = 'log_loss', n_estimators= 200)

final_model.fit(x_smote , y_smote)
final_model.fit(x_smote , y_smote)
y_pred = final_model.predict(x_test)
print(f"accuracy by gradient is : {accuracy_score(y_test , y_pred)}")

print(f"confusion matric : ")
print(confusion_matrix(y_test , y_pred))

accuracy by forest is : 0.9968
confusion matric :
[[ 684    1    0]
 [   0 1068    7]
 [   0    0  740]]

In [105]:
joblib.dump(final_model , 'patient_data.pkl')

['patient_data.pkl']